Traceback (most recent call last):
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/conda/envs/ofs/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/envs/ofs/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import rioxarray

shpmetos = shpmetos.to_crs("EPSG:4326")

clipped = dset.hs[0].rio.write_crs("EPSG:4326").rio.clip(shpmetos.geometry, shpmetos.crs, drop=True)

fig, ax = plt.subplots(figsize=(20, 20), subplot_kw={'projection': ccrs.PlateCarree()})
ax.set_extent([90, 145, -13, 10])
ax.coastlines('10m')
ax.add_feature(cartopy.feature.LAND, facecolor='lightgrey', edgecolor='black')

mag = ax.contourf(clipped.lon.data, clipped.lat.data, clipped.data, cmap='gist_ncar', transform=ccrs.PlateCarree())

shpmetos.plot(ax=ax, facecolor='none', edgecolor='black', linewidth=1, transform=ccrs.PlateCarree())

gl = ax.gridlines(draw_labels=True)
gl.top_labels = False
gl.right_labels = False

plt.colorbar(mag, shrink=.75, pad=0.05, orientation='horizontal')
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[18][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mrioxarray[39;00m
[32m      3[39m shpmetos = shpmetos.to_crs([33m"[39m[33mEPSG:4326[39m[33m"[39m)
[32m      5[39m clipped = dset.hs[[32m0[39m].rio.write_crs([33m"[39m[33mEPSG:4326[39m[33m"[39m).rio.clip(shpmetos.geometry, shpmetos.crs, drop=[38;5;28;01mTrue[39;00m)

[31mModuleNotFoundError[39m: No module named 'rioxarray'

